version: '3'

services:
  'demo-nextjs-v6-ui':
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: 'demo-nextjs-v6-ui'
    ports:
      - "3000:3000"
    volumes:
      - ./:/srv/www
    command: bash -c "cd /srv/www && npm install && npm run dev"
    # env_file:
    #   - ./path/to/.env
    # environment:
    #   EXAMPLE_VAR: 'true'
    #   EXAMPLE_VAR2: 'secret'
    # depends_on:
    #   - mongodb
    #   - rabbitmq

  # mongodb:
  #   image: mongo:latest
  #   container_name: "nextjs-mongodb"
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   volumes:
  #     - ./docker/mongodb/data/db:/data/db
  #   ports:
  #     - "27017:27017"
  #   command: mongod --smallfiles --logpath=/dev/null # --quiet

  # rabbitmq:
  #   image: rabbitmq
  #   ports:
  #     - "5672:5672"
  #   expose:
  #     - "5672"
